### ISSUE TITLE
pip installation problem

### ISSUE THREAD

**Issue by muqeem066** [AI4Bharat/indic-numtowords#2]
Processing c:\users\CC\downloads\indic_numtowords-1.0.2.tar.gz
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\CC\AppData\Local\Temp\pip-req-build-3pblmnl4\setup.py", line 4, in <module>
          long_description = f.read()
                             ^^^^^^^^
        File "C:\Users\CC\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 271: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by pmsmanishchauhan** [comment]
Can you guys release the pip version for this fix
